---
- block: #=====Block for Ubuntu=====

   - name: add repository elastic
     apt_repository:
       repo: deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main
       state: present

   - name: install software
     apt:
       name: "{{item}}"
       state: present
       update_cache: true
       cache_valid_time: 3600
     loop:
       - packetbeat=8.1.1
       - metricbeat=8.1.1
       - heartbeat-elastic=8.1.1
       - auditbeat=8.1.1

   - name: start and enable
     service:
       name: "{{ item }}"
       state: started
       enabled: yes
     loop:
       - packetbeat
       - metricbeat
       - heartbeat-elastic
       - auditbeat

   - name: copy config files for beats
     copy: src={{ item.src }} dest={{ item.dest }}
     loop:
       - { src: 'packetbeat.yml.j2', dest: '/etc/packetbeat/packetbeat.yml' }
       - { src: 'metricbeat.yml.j2', dest: '/etc/metricbeat/metricbeat.yml' }
       - { src: 'heartbeat.yml.j2', dest: '/etc/heartbeat/heartbeat.yml' }
       - { src: 'auditbeat.yml.j2', dest: '/etc/auditbeat/auditbeat.yml' }
     notify:
       - restart beats


   - name: copy config files
     template: src={{ item.src }} dest={{ item.dest }}
     loop:
       - { src: 'nginx.conf.j2', dest: '/etc/zabbix/nginx.conf' }
     notify:
       - restart restart beats

  when: ansible_distribution == "Ubuntu"
