---
#установка агентов elk стэка
- name: install packetbeat
  get_url:
   url="https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-7.16.0-amd64.deb"
   dest="~/"
- name: apt install zabbix 6.0 release in ubuntu
  apt: deb="https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-7.16.0-amd64.deb"



- name: install metricbeat
  get_url:
   url="https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.16.0-amd64.deb"
   dest="~/"
- name: apt install zabbix 6.0 release in ubuntu
  apt: deb="https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.16.0-amd64.deb"



- name: install heartbeat
  get_url:
   url="https://artifacts.elastic.co/downloads/beats/heartbeat/heartbeat-7.16.0-amd64.deb"
   dest="~/"
- name: apt install zabbix 6.0 release in ubuntu
  apt: deb="https://artifacts.elastic.co/downloads/beats/heartbeat/heartbeat-7.16.0-amd64.deb"


- name: install auditbeat
  get_url:
   url="https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-7.16.0-amd64.deb"
   dest="~/"
- name: apt install zabbix 6.0 release in ubuntu
  apt: deb="https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-7.16.0-amd64.deb"



- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600



- name: start and enable
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - metricbeat
    - auditbeat
    - heartbeat
    - packebeat

- name: copy config files for beats
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: '~/infra/ansible/roles/elk-beats/files/packetbeat.yml', dest: '/etc/packetbeat/packetbeat.yml' }
    - { src: '~/infra/ansible/roles/elk-beats/files/metricbeat.yml', dest: '/etc/metricbeat/metricbeat.yml' }
    - { src: '~/infra/ansible/roles/elk-beats/files/heartbeat.yml', dest: '/etc/heartbeat/heartbeat.yml' }
    - { src: '~/infra/ansible/roles/elk-beats/files/auditbeat.yml', dest: '/etc/auditbeat/auditbeat.yml' }
  notify:
    - restart beats
