---
- block: #=====Block for Ubuntu=====

   - name: add repository elastic
     apt_repository:
       repo: deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main
       state: present

   - name: install software
     apt:
       name: "{{item}}"
       state: present
       update_cache: true
       cache_valid_time: 3600
     loop:
       - packetbeat=8.1.1
       - metricbeat=8.1.1
       - heartbeat-elastic=8.1.1
       - auditbeat=8.1.1

   - name: start and enable
     service:
       name: "{{ item }}"
       state: started
       enabled: yes
     loop:
       - packetbeat
       - metricbeat
       - heartbeat-elastic
       - auditbeat

   - name: copy config files for beats
     copy: src={{ item.src }} dest={{ item.dest }}
     with_items:
       - { src: '~/infra/ansible/roles/elk-beats/files/packetbeat.yml', dest: '/etc/packetbeat/packetbeat.yml' }
       - { src: '~/infra/ansible/roles/elk-beats/files/metricbeat.yml', dest: '/etc/metricbeat/metricbeat.yml' }
       - { src: '~/infra/ansible/roles/elk-beats/files/heartbeat.yml', dest: '/etc/heartbeat/heartbeat.yml' }
       - { src: '~/infra/ansible/roles/elk-beats/files/auditbeat.yml', dest: '/etc/auditbeat/auditbeat.yml' }
     notify:
       - restart beats

  when: ansible_distribution == "Ubuntu"
