---
- block: #=====Block for Ubuntu=====

   - name: add repository elastic
     apt_repository:
       repo: deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main
       state: present

   - name: install software
     apt:
       name: "{{item}}"
       state: present
       update_cache: true
       cache_valid_time: 3600
     loop:
       - auditbeat=8.1.1
       - heartbeat-elastic=8.1.1
       - metricbeat=8.1.1
       - packetbeat=8.1.1

   - name: stopped before setup beats
     service:
       name: "{{ item }}"
       state: stopped
       enabled: yes
     loop:
       - auditbeat
       - heartbeat-elastic
       - metricbeat
       - packetbeat

   - name: auditbeat setup
     shell: auditbeat setup -e || true

   - name: heartbeat setup
     shell: heartbeat setup -e || true

   - name: metricbeat setup
     shell: metricbeat setup -e || true

   - name: packetbeat setup
     shell: packetbeat setup -e || true

   - name: start and enable
     service:
       name: "{{ item }}"
       state: started
       enabled: yes
     loop:
       - auditbeat
       - heartbeat-elastic
       - metricbeat
       - packetbeat

   - name: copy config files for beats
     template: src={{ item.src }} dest={{ item.dest }}
     loop:
       - { src: 'packetbeat.yml.j2', dest: '/etc/packetbeat/packetbeat.yml' }
       - { src: 'metricbeat.yml.j2', dest: '/etc/metricbeat/metricbeat.yml' }
       - { src: 'heartbeat.yml.j2', dest: '/etc/heartbeat/heartbeat.yml' }
       - { src: 'auditbeat.yml.j2', dest: '/etc/auditbeat/auditbeat.yml' }
     notify:
       - restart beats

  when: ansible_distribution == "Ubuntu"
