---
- name: download zabbix 6.0 ubuntu release deb file
  get_url:
    url: "http://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-1+ubuntu{{ ansible_distribution_version }}_all.deb"
    dest: "~/"

- name: apt install zabbix 6.0 release in ubuntu
  apt: deb="~/zabbix-release_6.0-1+ubuntu{{ ansible_distribution_version }}_all.deb"

- name: install software
  apt:
    name: "{{item}}"
    state: present
    update_cache: true
  loop:
    - zabbix-server-pgsql
    - zabbix-frontend-php
    - php7.4-pgsql #7.2 если ubuntu18
    - zabbix-nginx-conf
    - zabbix-sql-scripts
    - zabbix-agent
    - python3-psycopg2
    - acl

- name: install repo pgsql 14
  shell: |
    echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
  args:
    warn: no

- name: add apt signing key
  apt_key:
    url  : https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: install pgsql
  apt:
    name: postgresql-14
    state: present
    update_cache: true
  notify:
    - enable pgsql

- name: Create database user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: SUPERUSER

- name: Create a new database
  become_user: postgres
  community.general.postgresql_db:
    name: "{{ db_name }}"
    stat: present

- name: copy config files for zabbix-server
  copy: src={{ item.src }} dest={{ item.dest }}
  loop:
    - { src: '~/infra/ansible/roles/zabbix-server/files/zabbix_server.conf', dest: '/etc/zabbix/zabbix_server.conf' }
    - { src: '~/infra/ansible/roles/zabbix-server/files/php-fpm.conf', dest: '/etc/zabbix/php-fpm.conf' }
    - { src: '~/infra/ansible/roles/zabbix-server/files/zabbix.conf.php', dest: '/etc/zabbix/web/zabbix.conf.php' }
    - { src: '~/infra/ansible/roles/zabbix-server/files/nginx.conf', dest: '/etc/zabbix/nginx.conf' }
  notify:
    - restart services

- name: create symlink
  file:
    src  : /etc/zabbix/nginx.conf
    dest : /etc/nginx/sites-enabled/default
    state: link
