---
- name: download zabbix 6.0 ubuntu release deb file
  get_url:
    url: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-1+ubuntu{{ ansible_distribution_version }}_all.deb"
    dest: "~/"

- name: apt install zabbix 6.0 release in ubuntu
  apt: deb="~/zabbix-release_6.0-1+ubuntu{{ ansible_distribution_version }}_all.deb"

- name: install software
  apt:
    name: "{{item}}"
    state: present
    update_cache: true
    #cache_valid_time: 86400
  loop:
    - zabbix-server-pgsql
    - zabbix-frontend-php
    - php7.4-pgsql
    - zabbix-nginx-conf
    - zabbix-sql-scripts
    - zabbix-agent

- name: remove apache2 #зависимостями почему то устанавливается apache2. Это временно исправляет проблему
  apt:
    name: "{{item}}"
    state: absent
    update_cache: true
    #cache_valid_time: 86400
  loop:
    - apache2*

- name: rm apache2
  shell: apt remove -y apache2*

- name: install repo pgsql 14
  shell: |
    echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
  args:
    warn: no

- name: add apt signing key
  apt_key:
    url  : https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: install pgsql
  apt:
    name: postgresql-14
    update_cache: true
    #cache_valid_time: 3600
  notify:
    - enable pgsql

#создание пользователя и импорт таблицы вручную пока

- name: copy the nginx config file
  copy:
    src : ~/infra/ansible/roles/zabbix-server/files/nginx.conf
    dest: /etc/zabbix/nginx.conf
  notify:
    - restart nginx
- name: create symlink
  file:
    src  : /etc/zabbix/nginx.conf
    dest : /etc/nginx/sites-enabled/default
    state: link

- name: restart service
  service:
    name   : "{{item}}"
    state  : restarted
    enabled: yes
  loop:
    - zabbix-server
    - zabbix-agent
    - nginx
    - php7.4-fpm
