---
- block: #=====Block for Ubuntu=====

   - name: download zabbix 6.0 ubuntu release deb file
     get_url:
       url: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-1+ubuntu{{ ansible_distribution_version }}_all.deb"
       dest: "~/"

   - name: apt install zabbix 6.0 release in ubuntu
     apt: deb="~/zabbix-release_6.0-1+ubuntu{{ ansible_distribution_version }}_all.deb"

   - name: install software
     apt:
       name: "{{item}}"
       state: present
       update_cache: true
     loop:
       - zabbix-server-pgsql
       - zabbix-frontend-php
       - php7.2-pgsql
       - zabbix-nginx-conf
       - zabbix-sql-scripts
       - zabbix-agent

  when: ansible_distribution == "Ubuntu"
