---
- block: #=====Block for Ubuntu20.04=====

   - name: download zabbix 6.0 ubuntu release deb file
     get_url:
       url: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-1+ubuntu18.04_all.deb"
       dest: "~/"

   - name: apt install zabbix 6.0 release in ubuntu
     apt: deb="~/zabbix-release_6.0-1+ubuntu20.04_all.deb"

   - name: install software
     apt:
       name: "{{item}}"
       state: present
       update_cache: true
     loop:
       - zabbix-server-pgsql
       - zabbix-frontend-php
       - php7.2-pgsql #7.2 если ubuntu18
       - zabbix-nginx-conf
       - zabbix-sql-scripts
       - zabbix-agent
       - python3-psycopg2
       - acl

   - name: remove apache2 #Устанавливается по какой то причине с зависимостями. Это временное решение
     shell: apt remove -y apache2* && apt autoremove -y

   - name: install repo pgsql 14
     shell: echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
     args:
       warn: no

   - name: add apt signing key
     apt_key:
       url  : https://www.postgresql.org/media/keys/ACCC4CF8.asc
       state: present

   - name: install pgsql
     apt:
       name: postgresql-14
       state: present
       update_cache: true
     notify:
       - enable pgsql

   - name: Create database user
     become_user: postgres
     postgresql_user:
       name: "{{ zabbix_pg_db_user }}"
       password: "{{ zabbix_pg_db_password }}"
       role_attr_flags: SUPERUSER

   - name: Create a new database
     become_user: postgres
     community.general.postgresql_db:
       name="{{ zabbix_pg_db_name }}"
       state=present

   - name: copy config files
     template: src={{ item.src }} dest={{ item.dest }}
     loop:
       - { src: 'zabbix_server.conf.j2', dest: '/etc/zabbix/zabbix_server.conf', owner: 'zabbix', group: 'zabbix', mode: '0640'}
       - { src: 'nginx.conf.j2', dest: '/etc/zabbix/nginx.conf' }
     notify:
       - restart services

   - name: create symlink
     file:
       src  : /etc/zabbix/nginx.conf
       dest : /etc/nginx/sites-enabled/default
       state: link

   - name: import db schema
     shell: zcat /usr/share/doc/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix

  when: ansible_distribution_version == "18.04"
