---
- block: #=====Block for Ubuntu=====

   - name: install repo pgsql 14
     shell: echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
     args:
       warn: no

   - name: add apt signing key
     apt_key:
       url  : https://www.postgresql.org/media/keys/ACCC4CF8.asc
       state: present

   - name: install software
     apt:
       name: "{{item}}"
       state: present
       update_cache: true
     loop:
       - postgresql-14
       - python3-psycopg2
       - acl
     notify:
       - enable pgsql

   - name: Create database user
     become_user: postgres
     postgresql_user:
       name: "{{ pg_db_user }}"
       password: "{{ pg_db_password }}"
       #role_attr_flags: SUPERUSER
       state: present

   - name: Create a new database
     become_user: postgres
     community.general.postgresql_db:
       name: "{{ pg_db_name }}"
       state: present

  when: ansible_distribution == "Ubuntu"
