---
#nano /etc/lvm/lvm.conf
#use_lvmetad = 0
#dracut -H -f /boot/initramfs-$(uname -r).img $(uname -r)

- name: repos
  shell: systemctl start pcsd.service && systemctl enable pcsd.service

- name: start and enable
  shell: systemctl start pcsd.service && systemctl enable pcsd.service

- name: user
  shell: echo ‘12345678’ | passwd hacluster --stdin
###
- name: auth
  shell: pcs cluster auth -u hacluster -p 12345678 nfs1.albert-infra.local nfs2.albert-infra.local

- name: repos
  shell: pcs cluster setup --start --name NFS_DATA nfs1.albert-infra.site nfs2.albert-infra.site

- name: repos
  shell: pcs cluster enable –all && pcs cluster start –all

- name: repos
  shell: pcs property set stonith-enabled=false

- name: repos
  shell: pcs property set symmetric-cluster=true

- name: repos
  shell: pcs resource create CL_RS Filesystem device="/dev/vg01/lv01" directory="/mnt/data" fstype="ext4" --group UANFSHA
