---
- parted:
    device: "{{ device }}"
    number: 1
    state: present

- name: task for creating volume group
  lvg:
      vg: "{{ vg_name }}"
      pvs: "{{ partition }}"

- name: task for creating logical volume
  lvol:
      vg: "{{ vg_name }}"
      lv:  "{{ lv_name }}"
      size: +100%FREE
      resizefs: true

- name: create ext4 filesystem on lvm_storage
  filesystem:
    fstype: ext4
    dev: "{{ lvm_storage }}"

- name: creates directory for mountpoint
  file:
    path: "{{ mountpoint }}"
    state: directory

- name: mount fstab
  ansible.posix.mount:
    path: "{{ mountpoint }}"
    src: "{{ lvm_storage }}"
    fstype: ext4
    opts: noatime
    state: mounted
