---
- parted:
    device: /dev/sdb
    number: 1
    state: present

- name: task for creating volume group
  lvg:
      vg: vg01
      pvs: /dev/sdb1
      #pesize: 16

- name: task for creating logical volume
  lvol:
      vg: vg01
      lv:  lv01
      size: +100%FREE
      resizefs: true

- name: create ext4 filesystem on /dev/vg01/lv01
  filesystem:
    fstype: ext4
    dev: /dev/vg01/lv01
    force: yes

- name: creates directory /mnt/data
  file:
    path: /mnt/data
    state: directory
