---
- name: repos
  shell: dnf config-manager --set-enabled ha-source ha

- name: install based software
  dnf:
    name:
      - pcs
      - pacemaker
      - fence-agents-all
      - nfs-utils
      - psmisc
      - policycoreutils-python
    update_cache: true
    enablerepo: ha ha-sourse
    state: present



#dnf --enablerepo=HighAvailability -y install pacemaker pcs
