---
- block: #=====Block for Ubuntu=====

   - name: download zabbix 6.0 ubuntu release deb file
     get_url:
       url: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-1+ubuntu{{ ansible_distribution_version }}_all.deb"
       dest: "~/"

   - name: apt install zabbix 6.0 release in ubuntu
     apt: deb="~/zabbix-release_6.0-1+ubuntu{{ ansible_distribution_version }}_all.deb"

   - name: apt-get update
     apt:
       update_cache: true
       cache_valid_time: 3600

   - name: apt install zabbix agent 6.0
     apt: name=zabbix-agent state=present

   - name: copy config files
     template: src={{ item.src }} dest={{ item.dest }}
     loop:
       - { src: 'zabbix_agentd.conf.j2', dest: '/etc/zabbix/zabbix_agentd.conf' }
     notify:
      - restart agent

  when: ansible_distribution == "Ubuntu"
