---
- name: install software
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - gnupg2
    - pass
    - software-properties-common
    - mc
    - ntp
    - wget
    - git
    - ntp

- name: set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow

- name: copy config files
  template: src={{ item.src }} dest={{ item.dest }}
  loop:
    - { src: 'ntp.conf.j2', dest: '/etc/ntp.conf' }
  notify:
    - restart ntp
