---
- name: create physical slot to the database zabbix
  become_user: postgres
  postgresql_slot:
    name: physical_slot
    slot_type: physical
    immediately_reserve: yes
    state: present
    #output_plugin: custom_decoder_one
    db: zabbix
