---
- block: #=====Block for Ubuntu=====

   - name: Create database user
     become_user: postgres
     postgresql_user:
       name: "{{ pg_repl_user }}"
       password: "{{ pg_repl_password }}"
       role_attr_flags: SUPERUSER
       state: present

  when: ansible_distribution == "Ubuntu"
