#для разворачивания нового сервера приложения
---
- name: docker login
  docker_login:
    registry: "{{ registry }}"
    username: "{{ username }}"
    password: "{{ password }}"
    reauthorize: yes

- name: copy docker-compose.yml
  copy:
    src: /builds/my_projects/my_project1/docker-compose.yml
    dest: ~/docker-compose.yml

- name: deploy
  shell: docker-compose pull && docker-compose -f ~/docker-compose.yml up -d
