#для разворачивания нового сервера приложения
---
- name: docker login
  shell: docker login "{{ registry }}" -u "{{ username }}" -p "{{ password }}"

- name: template docker-compose.yml
  template: src=docker-compose.yml.j2 dest=~/docker-compose.yml

- name: deploy
  shell: docker-compose pull && docker-compose up -d
