---
- block: #=====Block for Ubuntu=====

   - name: add repository elastic
     apt_repository:
       repo: deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main
       state: present

   - name: install software
     apt:
       name: "{{item}}"
       state: present
       update_cache: true
       cache_valid_time: 3600
     loop:
       - auditbeat=8.1.1
       - heartbeat-elastic=8.1.1
       - metricbeat=8.1.1
       - filebeat=8.1.1

   - name: shell
     ansible.builtin.shell: "{{ item }}"
     loop:
       - systemctl stop auditbeat && auditbeat setup -e || true
       - systemctl stop heartbeat-elastic && heartbeat setup -e || true

       - systemctl stop metricbeat && metricbeat modules enable system docker elasticsearch-xpack || true
       - systemctl stop metricbeat && metricbeat setup -e || true

       - systemctl stop filebeat && filebeat modules enable auditd system elasticsearch || true
       - systemctl stop filebeat && filebeat setup -e || true

   - name: start and enable
     service:
       name: "{{ item }}"
       state: started
       enabled: yes
     loop:
       - auditbeat
       - heartbeat-elastic
       - metricbeat
       - filebeat

   - name: copy config files for beats
     template: src={{ item.src }} dest={{ item.dest }}
     loop:
       - { src: 'auditbeat.yml.j2', dest: '/etc/auditbeat/auditbeat.yml' }
       - { src: 'heartbeat.yml.j2', dest: '/etc/heartbeat/heartbeat.yml' }
       - { src: 'metricbeat.yml.j2', dest: '/etc/metricbeat/metricbeat.yml' }
       - { src: 'filebeat.yml.j2', dest: '/etc/filebeat/filebeat.yml' }

     notify:
       - restart beats

  when: ansible_distribution == "Ubuntu"
