---
#установка основного программного обеспечения
- block: #=====Block for Ubuntu=====
   - name: install software
     apt:
       name: "{{item}}"
       state: present
       update_cache: true
       cache_valid_time: 3600
     loop:
       - apt-transport-https
       - ca-certificates
       - curl
       - gnupg-agent
       - gnupg2
       - pass
       - software-properties-common
       - mc
       - ntp
       - wget
       - git
       - ntp
       - snapd

   - name: copy config files
     template: src={{ item.src }} dest={{ item.dest }}
     loop:
       - { src: 'ntp.conf.j2', dest: '/etc/ntp.conf', owner: 'albert', group: 'albert', mode: '0644'}
     notify:
       - restart ntp service

  when: ansible_distribution == "Ubuntu"

- name: set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow
