---
- name: install software
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - gnupg2
    - pass
    - software-properties-common
    - mc
    - ntp
    - wget
    - git

- name: install ntp
  apt: name=ntp state=latest

- name: install mc
  apt: name=mc state=latest

- name: set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow

- name: copy the ntp config file
  copy:
    src={{ ntp_conf_source }} dest={{ ntp_conf_dest }}
    owner=albert
    group=albert
    mode=0644
  notify:
    - restart ntp service
