---
#установка docker
- block: #=====Block for Ubuntu=====

   - name: add GPG key
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

   - name: add repository docker
     apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
       state: present

   - name: install docker
     apt:
       name: "{{item}}"
       state: present
       update_cache: true
       cache_valid_time: 3600
     loop:
       - docker-ce
       - docker-ce-cli
       - containerd.io

   - name: start and enable docker
     service:
         name: docker
         state: started
         enabled: yes

   - name: install docker-compose
     apt: pkg=docker-compose state=latest

   - name: add user albert for group docker
     user: name=albert
           group=docker
           shell=/bin/bash

  when: ansible_distribution == "Ubuntu"
