---
- name: install software
  hosts: all
  become: true
  roles:
  - general
  - zabbix-agent
- name: proxy server
  hosts: proxy
  become: true
  roles:
  - proxy
- name: web server
  hosts: web
  become: true
  roles:
  - docker
  - deploy
- name: mongodb
  hosts: mongo
  become: true
  roles:
  - mongo
