---
- name: install software
  hosts: all
  become: true
  roles:
  - general
  - zabbix-agent
  - elk-beats
- name: proxy server
  hosts: proxy
  become: true
  roles:
  - proxy
- name: web server
  hosts: web
  become: true
  roles:
  - docker
  - deploy


#ansible all -m shell -u albert -K -a "sudo apt-get update && sudo apt-get upgrade -y"
