---
- block: #=====Block for Ubuntu=====

   - name: install repo zabbix 5.0 for ubuntu
     apt:
       deb: http://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+bionic_all.deb

   - name: apt update
     apt:
       update_cache: yes
       cache_valid_time: 3600

   - name: install zabbix-agent
     apt: pkg=zabbix-agent state=latest

   - name: Creates directory
     file:
       path: /etc/zabbix/zabbix_agentd.d
       state: directory

  when: ansible_os_family == "Debian"

- name: copy the zabbix config file
  copy:
    src={{ source_conf }} dest={{ dest_conf }}
  notify:
    - restart zabbix-agent
