---
- block: #=====Block for Debian=====

   - name: install repo zabbix 6.0 for debian
     apt:
       deb: http://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-1+debian11_all.deb

   - name: apt update
     apt:
       update_cache: yes
       cache_valid_time: 86400

   - name: install zabbix-agent
     apt: pkg=zabbix-agent state=latest

   - name: creates directory
     file:
       path: /etc/zabbix/zabbix_agentd.d
       state: directory
       owner: "zabbix"
       group: "zabbix"
       recurse: yes

   - name: creates directory
     file:
       path: /var/log/zabbix
       state: directory
       owner: "zabbix"
       group: "zabbix"
       recurse: yes

   - name: copy the zabbix config file
     copy:
      src={{ source_conf }} dest={{ dest_conf }}
     notify:
      - restart agent

  when: ansible_os_family == "Debian"

- block: #=====Block for CentOS=====

   - name: install repo zabbix 6.0 for centos
     dnf:
       name: http://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-1.el8.noarch.rpm
       state: present

   - name: yum update
     dnf:
       update_cache: True
       cache_valid_time: 86400

   - name: install zabbix-agent
     dnf:
       name: zabbix-agent
       state: present

   - name: copy the zabbix config file
     copy:
       src={{ source_conf }} dest={{ dest_conf }}
     notify:
       - restart agent

  when: ansible_os_family == "RedHat"
