---
- block: #=====Block for Debian/Ubuntu=====

   - name: install repo zabbix 6.0 for debian
     apt:
       deb: http://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-1+debian11_all.deb

   - name: apt update
     apt:
       update_cache: yes
       cache_valid_time: 86400

   - name: install zabbix-agent
     apt: pkg=zabbix-agent state=latest

   - name: Creates directory
     file:
       path: /etc/zabbix/zabbix_agentd.d
       state: directory

  when: ansible_os_family == "Debian"

- name: copy the zabbix config file
  copy:
    src={{ source_conf }} dest={{ dest_conf }}
  notify:
    - restart zabbix-agent
