---
# handlers file for zabbix-server
- name: enable pgsql
  service: name=postgresql state=started enabled=yes

- name: restart services
  service:
    name: "{{item}}"
    state: restarted
  loop:
    - nginx
    - zabbix-server
