---
# handlers file for zabbix-server
- name: enable pgsql
  service: name=postgresql state=started enabled=yes

- name: restart nginx
  service: name=nginx state=restarted

- name: restart zabbix_server
  service: name=zabbix-server state=restarted

- name: restart services
  service:
    name   : "{{item}}"
    state  : restarted
    enabled: yes
  loop:
    - zabbix-server
    - nginx
    - php7.4-fpm #7.2 если ubuntu18
    - nginx
