---
- name: apt update
  apt:
    update_cache: true

- name: install nginx
  apt: pkg=nginx state=present

- name: start nginx
  service:
      name: nginx
      state: started
      enabled: yes

- name: nginx copy global config file
  copy:
    src={{ source_conf }} dest={{ dest_conf }}
  notify:
    - restart nginx
