---
- name: apt update
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: install nginx
  apt: pkg=nginx state=present

- name: start nginx
  service:
      name: nginx
      state: started
      enabled: yes

- name: copy config files nginx
  template: src={{ item.src }} dest={{ item.dest }}
  loop:
    - { src: 'nginx.conf.j2', dest: '/etc/nginx/nginx.conf' }
    - { src: 'default.j2', dest: '/etc/nginx/sites-available/proxy' }
  notify:
    - restart nginx


- name: create symlink
  file:
    src  : /etc/nginx/sites-available/proxy
    dest : /etc/nginx/sites-enabled/proxy
    state: link
